Review 1
git-jr/Concord pull request #2
Opened 2023-04-13 13:58 UTC by git-jr

2023-04-13 19:03 UTC, alexfelipe requested changes
Tudo certo tirando o que tá errado.

2023-04-13 19:03 UTC, alexfelipe commented on app/build.gradle
> +    id 'kotlinx-serialization' // Usando apenas para serialização temporária, remover quando trocar para Room
remover caso não precisar

2023-04-13 19:03 UTC, alexfelipe commented on app/build.gradle
> +    def nav_version = "2.6.0-alpha09"
é necessário usar a versão alpha?

2023-04-13 19:03 UTC, alexfelipe commented on app/build.gradle
> +    implementation 'androidx.compose.material3:material3:1.1.0-beta02'
tem algo da versão beta que é essencial?

2023-04-13 19:03 UTC, alexfelipe commented on app/schemas/com.alura.concord.database.ConcordDatabase/1.json
Não revisei por ser um arquivo gerado

2023-04-13 19:03 UTC, alexfelipe commented on app/src/main/java/com/alura/concord/data/Chat.kt
> +    val lastMessage: String = "",
se só existe uma mensagem, parece estranho ser identificada como uma mensagem final. Se a ideia é ter apenas uma mensagem, talvez pode remover o last

2023-04-13 19:03 UTC, alexfelipe commented on app/src/main/java/com/alura/concord/data/Image.kt
> +import android.net.Uri
Não me parece uma boa manter referências do sdk do Android, se possível, tente usar apenas valores que não dependam do SDK.

2023-04-13 19:03 UTC, alexfelipe commented on app/src/main/java/com/alura/concord/data/SampleData.kt
> +        mediaLink = "/data/user/0/com.alura.concord/app_temImages/94f077ed-a81f-4a74-ac5b-6e44130e80b1"
essas img precisam tomar cuidado, pois deve estar no dispositivo

2023-04-13 19:03 UTC, alexfelipe commented on app/src/main/java/com/alura/concord/database/ChatDao.kt
> +    fun getAll(): Flow<List<Chat>?>
Dado que é uma lista, não poderia lidar diretamente com uma vazia? Ou precisa ser necessariamente nullable?

2023-04-13 19:03 UTC, alexfelipe commented on app/src/main/java/com/alura/concord/database/MessageDao.kt
> +    fun getAll(): Flow<List<Message>?>
mesmo padrão sobre lidar com uma lista vazia

2023-04-13 19:03 UTC, alexfelipe commented on app/src/main/java/com/alura/concord/database/MessageDao.kt
> +    fun getByChatId(chatId: Long): Flow<List<Message>?>
aqui tbm

2023-04-13 19:03 UTC, alexfelipe commented on app/src/main/java/com/alura/concord/di/module/ViewModelModule.kt
> +    fun provideApplication(@ApplicationContext context: Context): ConcordApplication {
pq foi necessário criar essa dependência?

2023-04-13 19:03 UTC, alexfelipe commented on app/src/main/java/com/alura/concord/extensions/Extensions.kt
> +        this, message, if (longTime) {
a partir de 3 argumentos/parâmetros, talvez seja mais interessante separar em linhas exclusivas

2023-04-13 19:03 UTC, alexfelipe commented on app/src/main/java/com/alura/concord/medias/Medias.kt
> +        ) { uri ->
Acho que da pra colocar uma safe call para que o parametro já seja diferente de nulo, pois o else não tem fallback, ou seja, é apenas um log que poderia ser feito com um elvis expr da vida

2023-04-13 19:03 UTC, alexfelipe commented on app/src/main/java/com/alura/concord/medias/Medias.kt
> +                cursor?.use {
talvez de pra simplificar tbm, pode usar um scope func, no caso o run, ai dentro dele aplica o `use` e tbm pode usar os métodos `moveToFirst()` etc sem depender da existência da variável, caso queira manter o uso da variável, ai pode manter o uso de um let, por exemplo

2023-04-13 19:03 UTC, alexfelipe commented on app/src/main/java/com/alura/concord/medias/Medias.kt
> +                    try { // Android >13
código específico de versão do Android não precisa de ifs? Ou esse código não apresenta crashes em versões mais antigas?

2023-04-13 19:03 UTC, alexfelipe commented on app/src/main/java/com/alura/concord/medias/Medias.kt
> +                    } catch (e: Exception) {
exception muito genérica, o ideal é sempre pegar uma exception específica caso realize um passo extra. Em outras palavras, nesse tipo de integração é preferivel quebrar caso não saiba o problema e executar os passos necessários com as devidas verificações, como por exemplo, garantindo que um código será executado apenas em versões específicas do Android

2023-04-13 19:03 UTC, alexfelipe commented on app/src/main/java/com/alura/concord/medias/Medias.kt
> +                    cursor.close()
teoricamente, o `use` garante que o `close()` seja invocado ao sair da sua execução

2023-04-13 19:03 UTC, alexfelipe commented on app/src/main/java/com/alura/concord/medias/Medias.kt
> +fun createFileSelectionResult(
transformar em extension

2023-04-13 19:03 UTC, alexfelipe commented on app/src/main/java/com/alura/concord/medias/Medias.kt
> +        rememberLauncherForActivityResult(ActivityResultContracts.OpenDocument()) { uri ->
evitar a extração com um remember interno

2023-04-13 19:03 UTC, alexfelipe commented on app/src/main/java/com/alura/concord/medias/Medias.kt
> +                cursor?.use {
considerar o uso de scope

2023-04-13 19:03 UTC, alexfelipe commented on app/src/main/java/com/alura/concord/medias/Medias.kt
> +                    cursor.close()
fecha automaticamente

2023-04-13 19:03 UTC, alexfelipe commented on app/src/main/java/com/alura/concord/navigation/MessageGraph.kt
> +fun NavGraphBuilder.messageGraph(
tomar cuidado com o nome graph, utilize screen caso seja apenas 1 destino

2023-04-13 19:03 UTC, alexfelipe commented on app/src/main/java/com/alura/concord/ui/chat/MessageListScreen.kt
confiei na call

2023-04-13 19:03 UTC, alexfelipe commented on app/src/main/java/com/alura/concord/ui/chat/MessageListViewModel.kt
> +    private val application: ConcordApplication,
remover contexto de viewmodel

2023-04-13 19:03 UTC, alexfelipe commented on app/src/main/java/com/alura/concord/ui/chat/MessageListViewModel.kt
> +            messageDao.getByChatId(chatId).collect { messages ->
se preferir pode colocar um filtro de não nulos

2023-04-13 19:03 UTC, alexfelipe commented on app/src/main/java/com/alura/concord/ui/chat/MessageListViewModel.kt
> +            val chat = chatDao.getById(chatId).first()
se preferir pode usar scope func

2023-04-13 19:03 UTC, alexfelipe commented on app/src/main/java/com/alura/concord/ui/chat/MessageListViewModel.kt
> +    private suspend fun updateLastMessageChat(
refletir sobre refatorar a solução e usar o flow reativo com o room

2023-04-13 19:03 UTC, alexfelipe commented on app/src/main/java/com/alura/concord/ui/chat/MessageListViewModel.kt
> +            updateLastMessageChat(userMessage)
se considerar a solução reativa, esse código não deve ser mais necessário

2023-04-13 19:03 UTC, alexfelipe commented on app/src/main/java/com/alura/concord/ui/home/ChatListViewModel.kt
> +    private fun checkLastOpenChat() {
talvez não vai precisar mais

2023-04-13 19:03 UTC, alexfelipe commented on app/src/main/java/com/alura/concord/ui/theme/Theme.kt
agora sim, dark mode 😎

2023-04-13 19:03 UTC, alexfelipe commented on app/src/main/java/com/alura/concord/util/Date.kt
> +    val currentTime = Calendar.getInstance().time
ve se da pra usar o LocalDate

2023-04-13 19:03 UTC, alexfelipe commented on build.gradle
> -    id 'com.android.application' version '7.4.2' apply false
teve update no AS, pegar a versão mais recente do agp

2023-04-14 02:24 UTC, git-jr commented on app/build.gradle
> +    implementation 'androidx.compose.material3:material3:1.1.0-beta02'
Sim  o [ModalBottomSheet](https://github.com/git-jr/Concord/blob/review/app/src/main/java/com/alura/concord/ui/components/BottomSheetFiles.kt)

2023-04-14 02:29 UTC, git-jr commented on app/src/main/java/com/alura/concord/data/Chat.kt
> +    val lastMessage: String = "",
Faz sentido, mas a ideia é nesse ponto é lidar com a última mensagem de cada chat, vou optar por manter como está no momento

2023-04-14 02:36 UTC, git-jr commented on app/src/main/java/com/alura/concord/data/SampleData.kt
> +        mediaLink = "/data/user/0/com.alura.concord/app_temImages/94f077ed-a81f-4a74-ac5b-6e44130e80b1"
Sim pode deixar, esses "links" de img eu pretendo modificar em vídeo pra demonstrar justamente essa ideia "o arquivo precisa estar lá". Mas dei uma refinada nos formatos

2023-04-14 02:48 UTC, git-jr commented on app/src/main/java/com/alura/concord/database/ChatDao.kt
> +    fun getAll(): Flow<List<Chat>?>
Dá pra ser com valor vazio sim, adaptado

2023-04-14 02:51 UTC, git-jr commented on app/src/main/java/com/alura/concord/di/module/ViewModelModule.kt
> +    fun provideApplication(@ApplicationContext context: Context): ConcordApplication {
Essa era aquela pra injetar o Context no viewModel, vou remover

2023-04-14 02:57 UTC, git-jr commented on app/src/main/java/com/alura/concord/medias/Medias.kt
> +                cursor?.use {
Aplicado naquela refatoração que fizemos de tarde

2023-04-14 02:58 UTC, git-jr commented on app/src/main/java/com/alura/concord/medias/Medias.kt
> +                    try { // Android >13
Aplicado naquela refatoração que fizemos de tarde, if adicionado

2023-04-14 02:59 UTC, git-jr commented on app/src/main/java/com/alura/concord/medias/Medias.kt
> +                    } catch (e: Exception) {
Aplicado naquela refatoração que fizemos de tarde, troca do try cath por uso de ifs para atribuição condicional a variável "takeFlags"

2023-04-14 03:03 UTC, git-jr commented on app/src/main/java/com/alura/concord/navigation/MessageGraph.kt
> +fun NavGraphBuilder.messageGraph(
ok, alterado

2023-04-14 03:03 UTC, git-jr commented on app/src/main/java/com/alura/concord/ui/chat/MessageListViewModel.kt
> +    private val application: ConcordApplication,
removido

2023-04-14 03:10 UTC, git-jr commented on app/src/main/java/com/alura/concord/extensions/Extensions.kt
> +        this, message, if (longTime) {
Ok!

2023-04-14 03:27 UTC, git-jr commented on app/src/main/java/com/alura/concord/util/Date.kt
> +    val currentTime = Calendar.getInstance().time
Atualizado

2023-04-14 03:29 UTC, git-jr commented on build.gradle
> -    id 'com.android.application' version '7.4.2' apply false
Atualizado

2023-04-14 18:01 UTC, alexfelipe approved these changes
tudo certo tirando o que tá errado

2023-04-14 18:01 UTC, alexfelipe commented on app/src/main/java/com/alura/concord/MainActivity.kt
> +                val navController = rememberNavController()
remover o código de debugging

2023-04-14 18:01 UTC, alexfelipe commented on app/src/main/java/com/alura/concord/navigation/ChatListScreen.kt
> +//        LaunchedEffect(Unit) {
tira o comentário antes de gravar, quando for usar ai coloca

2023-04-14 18:01 UTC, alexfelipe commented on app/src/main/java/com/alura/concord/navigation/ConcordNavHost.kt
> +//        startDestination = "messages/2",
remover comentário

2023-04-16 13:34 UTC, merged